package com.lyihub.archiveassistant.domain

object SampleKnowledgeData {
    const val DefaultTopicId = "topic-ai-architecture"
    const val DemoDataVersion = 2

    val topics: List<Topic> = listOf(
        demoTopic(DefaultTopicId, "大模型架构研究", "#B83E2F", 0),
        demoTopic("topic-ui-inspiration", "UX/UI 灵感板", "#D1A36B", 1),
        demoTopic("topic-anthropology-clips", "阅读剪报：人类学", "#8B654A", 2),
        demoTopic("topic-hidden-travel", "冷门旅行地参考", "#E65D3F", 3),
        demoTopic("topic-open-source-tools", "开源工具收藏", "#3E3E46", 4),
        demoTopic("topic-knowledge-workflows", "知识管理方法", "#78ABCC", 5),
    )

    val items: List<KnowledgeItem> = listOf(
        demoItem(
            id = "ai-001-rag-pipeline",
            topicId = DefaultTopicId,
            type = ContentType.WEB_ARTICLE,
            title = "RAG 系统从检索到生成的基本链路",
            summary = "面向演示的 RAG 架构笔记：索引、召回、重排、上下文拼装和回答生成如何串联。",
            tags = listOf("RAG", "检索增强", "架构"),
            sourceTitle = "中文技术博客与云厂商 RAG 实践资料整理",
            sourceUrl = "https://aws.amazon.com/cn/blogs/china/",
            body = "RAG 并不是单纯把搜索结果塞给模型，而是一条从资料清洗、向量化、召回、重排到提示词拼接的工程链路。演示时可突出它适合知识库问答、客服和企业文档检索，但需要处理召回质量、时效性和引用可信度。",
            dayOffset = 0,
        ),
        demoItem(
            id = "ai-002-moe-routing",
            topicId = DefaultTopicId,
            type = ContentType.WEB_ARTICLE,
            title = "MoE：用专家路由扩展模型容量",
            summary = "解释 MoE 如何在参数规模和推理成本之间做取舍，适合作为大模型架构卡片。",
            tags = listOf("MoE", "专家模型", "推理成本"),
            sourceTitle = "大模型 MoE 架构中文解读资料整理",
            sourceUrl = "https://www.infoq.cn/",
            body = "混合专家模型通过路由器选择少量专家参与计算，让模型拥有更大的总参数量，同时控制每次推理的激活参数。它的优势是容量扩展，难点是负载均衡、通信开销和训练稳定性。",
            dayOffset = 1,
        ),
        demoItem(
            id = "ai-003-agent-tool-use",
            topicId = DefaultTopicId,
            type = ContentType.DOCUMENT,
            title = "Agent 工具调用的任务循环",
            summary = "把 Agent 拆成目标理解、计划、工具调用、观察和修正几个环节。",
            tags = listOf("Agent", "工具调用", "任务规划"),
            sourceTitle = "Agent 开发中文文章摘要",
            sourceUrl = "https://developer.volcengine.com/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "Agent 的关键不是聊天界面，而是让模型能围绕目标持续选择工具、读取结果并修正下一步。演示中可以用抓取网页、生成摘要、保存到文件夹的流程解释它和普通问答的区别。",
            dayOffset = 2,
        ),
        demoItem(
            id = "ai-004-long-context",
            topicId = DefaultTopicId,
            type = ContentType.WEB_ARTICLE,
            title = "长上下文模型的机会与限制",
            summary = "长上下文能减少切片检索，但仍需要信息定位、压缩和成本控制。",
            tags = listOf("长上下文", "上下文工程", "成本"),
            sourceTitle = "长上下文模型中文评测与实践资料整理",
            sourceUrl = "https://www.jiqizhixin.com/",
            body = "长上下文窗口让模型一次读取更多材料，但并不等于理解能力线性提升。真实应用仍要关注关键信息位置、上下文稀释、输入费用和响应延迟，因此常与 RAG、摘要缓存配合使用。",
            dayOffset = 3,
        ),
        demoItem(
            id = "ai-005-multimodal",
            topicId = DefaultTopicId,
            type = ContentType.IMAGE_SCREENSHOT,
            title = "多模态模型如何理解截图与图表",
            summary = "用于演示图像类资料：模型可读 UI 截图、图表和文档页面，但需要清晰输入。",
            tags = listOf("多模态", "图像理解", "截图"),
            sourceTitle = "多模态大模型中文产品与技术资料整理",
            sourceUrl = "https://www.qbitai.com/",
            body = "多模态能力把图片、文本和结构化信息放到同一任务中处理。适合收藏 UI 截图、论文图表和产品页面，但演示时要说明：图片越清晰、版面越规整，模型提取结构越稳定。",
            dayOffset = 4,
        ),
        demoItem(
            id = "ai-006-evaluation",
            topicId = DefaultTopicId,
            type = ContentType.DOCUMENT,
            title = "大模型评测不只是跑分",
            summary = "评测应覆盖任务成功率、幻觉、延迟、成本和人工复核体验。",
            tags = listOf("评测", "幻觉", "质量"),
            sourceTitle = "大模型评测方法中文资料整理",
            sourceUrl = "https://www.msra.cn/",
            documentFormat = DocumentFormat.TXT,
            body = "模型评测需要结合具体任务，而不是只看排行榜。知识整理类应用尤其要记录来源、判断摘要是否忠于原文，并把不可确定的内容标注出来，避免把流畅表达误当成事实。",
            dayOffset = 5,
        ),
        demoItem(
            id = "ai-007-edge-ai",
            topicId = DefaultTopicId,
            type = ContentType.WEB_ARTICLE,
            title = "端侧大模型与隐私场景",
            summary = "端侧模型强调低延迟、离线可用和隐私保护，但受限于算力与模型大小。",
            tags = listOf("端侧 AI", "隐私", "推理"),
            sourceTitle = "端侧 AI 中文资料整理",
            sourceUrl = "https://www.leiphone.com/",
            body = "把模型部署在手机或 PC 本地，可以减少网络依赖，并让隐私敏感内容不必上传服务器。缺点是模型容量、能耗和散热受限，因此常见做法是端云协同：简单任务本地完成，复杂任务转云端。",
            dayOffset = 6,
        ),
        demoItem(
            id = "ai-008-prompt-engineering",
            topicId = DefaultTopicId,
            type = ContentType.DOCUMENT,
            title = "提示词工程转向上下文工程",
            summary = "从写一句 prompt，升级为组织材料、约束格式、定义评估和回收反馈。",
            tags = listOf("提示词", "上下文工程", "工作流"),
            sourceTitle = "Prompt Engineering 中文实践资料整理",
            sourceUrl = "https://github.com/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "提示词工程的重点正在从措辞技巧转向上下文组织。对资料应用来说，真正影响结果的是输入材料是否干净、标签是否清晰、输出结构是否稳定，以及用户是否能追溯原文。",
            dayOffset = 7,
        ),
        demoItem(
            id = "ai-009-model-compression",
            topicId = DefaultTopicId,
            type = ContentType.WEB_ARTICLE,
            title = "量化、蒸馏与小模型部署",
            summary = "小模型部署常用量化和蒸馏降低成本，适合端侧或私有化场景。",
            tags = listOf("量化", "蒸馏", "小模型"),
            sourceTitle = "模型压缩中文技术资料整理",
            sourceUrl = "https://www.csdn.net/",
            body = "量化通过降低权重精度减少显存和计算开销；蒸馏则让小模型学习大模型的行为。它们适合成本敏感场景，但需要重新评估关键任务的准确率与稳定性。",
            dayOffset = 8,
        ),
        demoItem(
            id = "ai-010-ai-infra",
            topicId = DefaultTopicId,
            type = ContentType.WEB_ARTICLE,
            title = "大模型应用的工程基础设施",
            summary = "从模型服务、缓存、向量库到监控，整理一条应用落地所需的工程栈。",
            tags = listOf("AI Infra", "向量库", "监控"),
            sourceTitle = "AI Infra 中文文章资料整理",
            sourceUrl = "https://www.infoq.cn/",
            body = "大模型应用需要的不只是模型 API，还包括鉴权、限流、提示词版本、向量索引、缓存、日志、评测集和成本监控。演示中可把它作为从原型走向产品的基础设施清单。",
            dayOffset = 9,
        ),
        demoItem(
            id = "ui-001-design-tokens",
            topicId = "topic-ui-inspiration",
            type = ContentType.WEB_ARTICLE,
            title = "Design Tokens 让视觉规范可复用",
            summary = "颜色、字号、间距和圆角等设计决策可以沉淀为跨端 token。",
            tags = listOf("Design Tokens", "设计系统", "规范"),
            sourceTitle = "中文设计系统文章整理",
            sourceUrl = "https://www.uisdc.com/",
            body = "Design Tokens 把颜色、字号、阴影、间距等视觉参数变成命名变量，方便设计和开发保持一致。演示时可用它解释为什么同一类卡片的圆角和标题层级不能随意变化。",
            dayOffset = 10,
        ),
        demoItem(
            id = "ui-002-foldable-layout",
            topicId = "topic-ui-inspiration",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "折叠屏左右分栏的阅读节奏",
            summary = "左侧导航、右侧内容的结构适合内屏演示，但需要固定宽度和清晰焦点。",
            tags = listOf("折叠屏", "分栏", "信息架构"),
            sourceTitle = "折叠屏应用设计中文资料整理",
            sourceUrl = "https://developer.huawei.com/consumer/cn/",
            body = "折叠屏展开后不是简单放大手机界面，而是要重新分配导航、内容和操作区域。左侧适合保持入口与状态，右侧适合承载当前任务，避免空白和临时入口。",
            dayOffset = 11,
        ),
        demoItem(
            id = "ui-003-masonry-feed",
            topicId = "topic-ui-inspiration",
            type = ContentType.WEB_ARTICLE,
            title = "瀑布流适合灵感与资料卡片",
            summary = "两列瀑布流能同时展示不同高度内容，适合图片和短文本混合。",
            tags = listOf("瀑布流", "信息流", "卡片"),
            sourceTitle = "小红书式内容流中文设计资料整理",
            sourceUrl = "https://www.uisdc.com/",
            body = "瀑布流的优势是高效利用纵向空间，尤其适合灵感图、文章摘录和短标题混排。需要注意的是标签和标题不能喧宾夺主，卡片间距也要保持统一节奏。",
            dayOffset = 12,
        ),
        demoItem(
            id = "ui-004-typography-hierarchy",
            topicId = "topic-ui-inspiration",
            type = ContentType.DOCUMENT,
            title = "移动端标题层级的字号控制",
            summary = "主标题、区域标题、卡片标题和标签应形成稳定层级。",
            tags = listOf("字体", "层级", "移动端"),
            sourceTitle = "中文字体排版设计资料整理",
            sourceUrl = "https://www.uisdc.com/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "优秀的移动端排版不会让所有标题都一样大。应用名称应是最高层级，右侧页面标题次之，卡片标题再降一级，标签则用于辅助检索而不是抢占视觉中心。",
            dayOffset = 13,
        ),
        demoItem(
            id = "ui-005-micro-interaction",
            topicId = "topic-ui-inspiration",
            type = ContentType.WEB_ARTICLE,
            title = "微交互让复杂操作更可感知",
            summary = "切换、拖动、回弹和选中态能降低用户理解成本。",
            tags = listOf("微交互", "动画", "反馈"),
            sourceTitle = "交互动效中文文章整理",
            sourceUrl = "https://www.ui.cn/",
            body = "微交互不是装饰，而是让用户知道系统正在响应。比如轮盘的吸附、卡片的按压、标签的激活状态，都能帮助用户理解当前焦点和下一步操作。",
            dayOffset = 14,
        ),
        demoItem(
            id = "ui-006-empty-state",
            topicId = "topic-ui-inspiration",
            type = ContentType.DOCUMENT,
            title = "空状态不应该只是空白",
            summary = "当没有选择或没有内容时，界面仍需给出默认任务或当前状态。",
            tags = listOf("空状态", "默认页", "可用性"),
            sourceTitle = "空状态设计中文资料整理",
            sourceUrl = "https://www.uisdc.com/",
            documentFormat = DocumentFormat.TXT,
            body = "空状态是产品体验的一部分。如果右侧没有选中内容，可以展示默认任务、最近内容或下一步入口，而不是留一大片空白区域让用户猜测。",
            dayOffset = 15,
        ),
        demoItem(
            id = "ui-007-card-density",
            topicId = "topic-ui-inspiration",
            type = ContentType.WEB_ARTICLE,
            title = "工具型应用的卡片密度控制",
            summary = "运营工具和资料工具应避免过度装饰，优先保证扫描效率。",
            tags = listOf("卡片", "密度", "效率"),
            sourceTitle = "SaaS 与工具型界面中文设计资料整理",
            sourceUrl = "https://www.uisdc.com/",
            body = "工具型应用不是营销页。卡片可以有质感，但信息密度、对齐、状态和操作路径更重要。过大的留白会让页面显得空，过多边框又会显得碎。",
            dayOffset = 16,
        ),
        demoItem(
            id = "ui-008-color-system",
            topicId = "topic-ui-inspiration",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "暖色纸感界面的颜色克制",
            summary = "米白、朱红、棕金等颜色适合国风主题，但需要限制色彩数量。",
            tags = listOf("配色", "国风", "视觉规范"),
            sourceTitle = "中国传统色与界面设计资料整理",
            sourceUrl = "https://colors.ichuantong.cn/",
            body = "国风界面容易陷入厚重和杂乱。更稳妥的做法是用米白做大面积底色，朱红做强调，棕金做边界和辅助信息，并控制彩色文字的使用。",
            dayOffset = 17,
        ),
        demoItem(
            id = "ui-009-icon-language",
            topicId = "topic-ui-inspiration",
            type = ContentType.WEB_ARTICLE,
            title = "图标比说明文字更适合工具入口",
            summary = "常见操作应用图标承载，陌生操作再配简短文字或 tooltip。",
            tags = listOf("图标", "工具栏", "交互"),
            sourceTitle = "移动端图标设计中文资料整理",
            sourceUrl = "https://www.iconfont.cn/",
            body = "图标能降低按钮体积，提升工具栏密度。保存、搜索、设置、返回等高频操作不必用大段文字解释，但领域特有功能可以保留短标题帮助识别。",
            dayOffset = 18,
        ),
        demoItem(
            id = "ui-010-native-dialog",
            topicId = "topic-ui-inspiration",
            type = ContentType.DOCUMENT,
            title = "系统默认弹窗会破坏视觉连续性",
            summary = "定制弹窗应继承应用字体、颜色、按钮和卡片风格。",
            tags = listOf("弹窗", "一致性", "组件"),
            sourceTitle = "Android Compose 弹窗设计资料整理",
            sourceUrl = "https://developer.android.google.cn/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "当应用已经建立清晰的视觉语言后，系统默认弹窗会显得突兀。更好的做法是封装统一 Dialog 组件，让标题、正文、按钮和背景都继承当前设计系统。",
            dayOffset = 19,
        ),
        demoItem(
            id = "anth-001-fieldwork",
            topicId = "topic-anthropology-clips",
            type = ContentType.WEB_ARTICLE,
            title = "田野调查为什么强调长期在场",
            summary = "田野调查通过长期观察和访谈理解地方社会，而不只是收集问卷。",
            tags = listOf("田野调查", "方法", "观察"),
            sourceTitle = "人类学田野方法中文资料整理",
            sourceUrl = "https://www.sohu.com/",
            body = "田野调查重视人在现场的持续参与。研究者通过观察、访谈、记录仪式和日常互动，理解当地人如何解释自己的生活，而不是只把他们当作数据点。",
            dayOffset = 20,
        ),
        demoItem(
            id = "anth-002-digital-anthropology",
            topicId = "topic-anthropology-clips",
            type = ContentType.WEB_ARTICLE,
            title = "数字人类学关注线上生活如何形成社区",
            summary = "社交平台、游戏和论坛都可以成为田野现场。",
            tags = listOf("数字人类学", "社区", "平台"),
            sourceTitle = "数字人类学中文文章整理",
            sourceUrl = "https://www.thepaper.cn/",
            body = "数字人类学把线上平台视为真实社会关系的一部分。弹幕、群聊、帖子和算法推荐都会影响身份、亲密关系和公共讨论的形成。",
            dayOffset = 21,
        ),
        demoItem(
            id = "anth-003-ritual",
            topicId = "topic-anthropology-clips",
            type = ContentType.DOCUMENT,
            title = "仪式不是表演，而是社会关系的重组",
            summary = "仪式常常用固定程序处理身份、秩序和情感。",
            tags = listOf("仪式", "社会关系", "象征"),
            sourceTitle = "仪式人类学中文读书笔记整理",
            sourceUrl = "https://book.douban.com/",
            documentFormat = DocumentFormat.TXT,
            body = "仪式把抽象关系变成可见行动。婚礼、祭祀、毕业典礼都不只是表演，而是在固定形式中确认身份转换、群体边界和共享记忆。",
            dayOffset = 22,
        ),
        demoItem(
            id = "anth-004-gift-exchange",
            topicId = "topic-anthropology-clips",
            type = ContentType.WEB_ARTICLE,
            title = "礼物交换背后的义务与关系",
            summary = "送礼、回礼和欠情构成社会网络的一部分。",
            tags = listOf("礼物", "交换", "关系"),
            sourceTitle = "礼物理论中文资料整理",
            sourceUrl = "https://www.douban.com/",
            body = "礼物不是免费的物品流动。它往往包含接受、回报和维持关系的义务，因此能体现亲疏、地位和共同体规则。",
            dayOffset = 23,
        ),
        demoItem(
            id = "anth-005-urban-village",
            topicId = "topic-anthropology-clips",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "城中村研究中的空间与流动人口",
            summary = "城中村是城市更新、租住网络和地方经济交织的现场。",
            tags = listOf("城中村", "城市研究", "流动"),
            sourceTitle = "城市人类学中文资料整理",
            sourceUrl = "https://www.archiposition.com/",
            body = "城中村不是城市边角料，而是低成本居住、劳动机会和熟人网络的节点。研究它需要同时观察空间形态、租赁关系和居民日常。",
            dayOffset = 24,
        ),
        demoItem(
            id = "anth-006-food-culture",
            topicId = "topic-anthropology-clips",
            type = ContentType.WEB_ARTICLE,
            title = "饮食如何保存地方记忆",
            summary = "食物连接家庭、迁徙和节日，是观察文化变化的入口。",
            tags = listOf("饮食", "地方记忆", "家庭"),
            sourceTitle = "饮食人类学中文文章整理",
            sourceUrl = "https://www.chinadaily.com.cn/",
            body = "一道菜常常包含迁徙路线、家庭分工和地方身份。饮食研究不只关心味道，也关心谁来做、什么时候吃、如何被讲述。",
            dayOffset = 25,
        ),
        demoItem(
            id = "anth-007-material-culture",
            topicId = "topic-anthropology-clips",
            type = ContentType.DOCUMENT,
            title = "物质文化：器物如何讲述生活方式",
            summary = "器物、服饰和居住空间都能成为理解社会的线索。",
            tags = listOf("物质文化", "器物", "日常"),
            sourceTitle = "物质文化研究中文资料整理",
            sourceUrl = "https://www.ihchina.cn/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "物质文化关注人如何使用、保存和赋予物品意义。一个箱子、一件衣服或一间厨房，都可能揭示家庭结构、性别分工和消费变迁。",
            dayOffset = 26,
        ),
        demoItem(
            id = "anth-008-oral-history",
            topicId = "topic-anthropology-clips",
            type = ContentType.WEB_ARTICLE,
            title = "口述史与个人记忆的可信度",
            summary = "口述史不是寻找绝对事实，而是理解人如何记忆和解释经历。",
            tags = listOf("口述史", "记忆", "访谈"),
            sourceTitle = "口述史方法中文资料整理",
            sourceUrl = "https://www.cssn.cn/",
            body = "口述材料需要和档案、场景、时间线互相参照。矛盾并不一定意味着无效，它也可能揭示叙事者如何理解创伤、身份或时代变化。",
            dayOffset = 27,
        ),
        demoItem(
            id = "anth-009-nonhuman",
            topicId = "topic-anthropology-clips",
            type = ContentType.WEB_ARTICLE,
            title = "多物种民族志把动物和环境纳入社会关系",
            summary = "生态、动物和微生物也会影响人的制度与日常。",
            tags = listOf("多物种", "生态", "民族志"),
            sourceTitle = "多物种民族志中文资料整理",
            sourceUrl = "https://www.thepaper.cn/",
            body = "多物种民族志试图跳出只研究人的框架，观察人、动物、植物、病毒和环境如何共同塑造社会生活。它适合用于理解农业、城市生态和公共卫生议题。",
            dayOffset = 28,
        ),
        demoItem(
            id = "anth-010-ethics",
            topicId = "topic-anthropology-clips",
            type = ContentType.DOCUMENT,
            title = "田野伦理：记录之前先建立信任",
            summary = "研究者需要处理知情同意、隐私保护和材料使用边界。",
            tags = listOf("伦理", "隐私", "知情同意"),
            sourceTitle = "社会研究伦理中文资料整理",
            sourceUrl = "https://www.pku.edu.cn/",
            documentFormat = DocumentFormat.TXT,
            body = "田野记录不能只追求材料丰富。研究者需要说明用途、保护匿名、尊重拒访，并在发布时避免让被研究者承担额外风险。",
            dayOffset = 29,
        ),
        demoItem(
            id = "travel-001-quanzhou",
            topicId = "topic-hidden-travel",
            type = ContentType.WEB_ARTICLE,
            title = "泉州：在寺庙与骑楼之间看海丝城市",
            summary = "泉州适合慢行，重点是宗教建筑、老街和地方小吃。",
            tags = listOf("泉州", "海丝", "城市漫游"),
            sourceTitle = "泉州旅行中文攻略资料整理",
            sourceUrl = "https://www.mafengwo.cn/",
            body = "泉州的看点不在打卡速度，而在开元寺、清净寺、关岳庙和老街之间的日常生活。适合安排两到三天，用步行串起建筑、香火和小吃。",
            dayOffset = 30,
        ),
        demoItem(
            id = "travel-002-dali-nuodeng",
            topicId = "topic-hidden-travel",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "诺邓古村：盐井与火腿留下的山村纹理",
            summary = "云南诺邓适合观察山地村落、盐业遗迹和慢节奏生活。",
            tags = listOf("诺邓", "古村", "云南"),
            sourceTitle = "诺邓旅行中文攻略资料整理",
            sourceUrl = "https://www.xiaohongshu.com/",
            body = "诺邓的体验重点是村路、盐井、古宅和火腿作坊。交通不如热门古城方便，但也因此保留了更安静的山村节奏。",
            dayOffset = 31,
        ),
        demoItem(
            id = "travel-003-jingdezhen",
            topicId = "topic-hidden-travel",
            type = ContentType.WEB_ARTICLE,
            title = "景德镇不只买陶瓷，也适合看手作流程",
            summary = "从陶溪川到工作室，适合观察传统工艺和青年创作。",
            tags = listOf("景德镇", "手作", "陶瓷"),
            sourceTitle = "景德镇旅行中文攻略资料整理",
            sourceUrl = "https://www.mafengwo.cn/",
            body = "景德镇的旅行可以从陶瓷市场扩展到工坊、展览和窑址。它适合对材料、器物和手作感兴趣的人，而不是单纯购物。",
            dayOffset = 32,
        ),
        demoItem(
            id = "travel-004-yanbian",
            topicId = "topic-hidden-travel",
            type = ContentType.WEB_ARTICLE,
            title = "延边：边境城市里的双语招牌与冷面",
            summary = "延吉和图们适合体验边境文化、朝鲜族饮食和城市街景。",
            tags = listOf("延边", "边境", "饮食"),
            sourceTitle = "延边旅行中文攻略资料整理",
            sourceUrl = "https://www.qyer.com/",
            body = "延边旅行的魅力在城市细节：双语招牌、市场、冷面、烤肉和图们江边境风景。适合安排轻松城市漫游，而不是高强度景点路线。",
            dayOffset = 33,
        ),
        demoItem(
            id = "travel-005-libo",
            topicId = "topic-hidden-travel",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "荔波小七孔：喀斯特水色与步道节奏",
            summary = "适合自然风景演示，图片和短文本混合展示效果好。",
            tags = listOf("荔波", "喀斯特", "自然"),
            sourceTitle = "贵州荔波中文攻略资料整理",
            sourceUrl = "https://www.ctrip.com/",
            body = "荔波的重点是水色、瀑布、森林和桥。更适合早进景区慢慢走，避开人流高峰；资料卡片中可用图片展示自然色彩。",
            dayOffset = 34,
        ),
        demoItem(
            id = "travel-006-shaxi",
            topicId = "topic-hidden-travel",
            type = ContentType.WEB_ARTICLE,
            title = "沙溪古镇：茶马古道上的安静停顿",
            summary = "相比热门古城，沙溪更适合慢住、看集市和村落。",
            tags = listOf("沙溪", "古镇", "慢旅行"),
            sourceTitle = "沙溪旅行中文攻略资料整理",
            sourceUrl = "https://www.qyer.com/",
            body = "沙溪的节奏比大理古城更慢，古戏台、寺登街、周边村落和集市构成主要体验。适合做一张强调慢旅行的演示卡。",
            dayOffset = 35,
        ),
        demoItem(
            id = "travel-007-wuyuan",
            topicId = "topic-hidden-travel",
            type = ContentType.WEB_ARTICLE,
            title = "婺源非花季也有徽派村落和晒秋",
            summary = "婺源不只油菜花，秋季村落和建筑同样适合深度游。",
            tags = listOf("婺源", "徽派", "村落"),
            sourceTitle = "婺源旅行中文攻略资料整理",
            sourceUrl = "https://www.mafengwo.cn/",
            body = "很多人只在油菜花季去婺源，但非花季也能看村落、祠堂、溪流和晒秋。更好的路线是避开单点打卡，选择几个村子慢慢看。",
            dayOffset = 36,
        ),
        demoItem(
            id = "travel-008-aksu",
            topicId = "topic-hidden-travel",
            type = ContentType.DOCUMENT,
            title = "阿克苏周边的峡谷、胡杨与公路",
            summary = "南疆旅行资料，适合作为长线规划片段。",
            tags = listOf("南疆", "阿克苏", "公路"),
            sourceTitle = "南疆旅行中文攻略资料整理",
            sourceUrl = "https://www.mafengwo.cn/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "阿克苏周边适合连接峡谷、胡杨林和公路风景。长线旅行需要关注季节、车程、补给和安全边界，适合作为规划类资料卡。",
            dayOffset = 37,
        ),
        demoItem(
            id = "travel-009-chishui",
            topicId = "topic-hidden-travel",
            type = ContentType.WEB_ARTICLE,
            title = "赤水丹霞：瀑布、竹海与红色岩壁",
            summary = "贵州赤水适合自然景观和低密度旅行素材。",
            tags = listOf("赤水", "丹霞", "瀑布"),
            sourceTitle = "赤水旅行中文攻略资料整理",
            sourceUrl = "https://www.ctrip.com/",
            body = "赤水的自然景观由丹霞地貌、瀑布和竹海组成。相比热门山岳景区，它更适合做低密度自然旅行的资料示例。",
            dayOffset = 38,
        ),
        demoItem(
            id = "travel-010-dongshan",
            topicId = "topic-hidden-travel",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "东山岛：海边县城的风与旧街",
            summary = "福建海岛资料，适合图片卡与短标题展示。",
            tags = listOf("东山岛", "海岛", "福建"),
            sourceTitle = "东山岛旅行中文攻略资料整理",
            sourceUrl = "https://www.xiaohongshu.com/",
            body = "东山岛的重点是海湾、旧街、风动石和海鲜市场。它适合用轻量图文卡展示，不需要特别长的攻略正文。",
            dayOffset = 39,
        ),
        demoItem(
            id = "tool-001-obsidian",
            topicId = "topic-open-source-tools",
            type = ContentType.WEB_ARTICLE,
            title = "Obsidian：本地 Markdown 知识库",
            summary = "适合作为个人资料库示例，强调双链、插件和本地文件。",
            tags = listOf("Markdown", "双链", "知识库"),
            sourceTitle = "Obsidian 中文社区资料整理",
            sourceUrl = "https://obsidian.md/",
            body = "Obsidian 使用本地 Markdown 文件组织笔记，通过双链和插件扩展工作流。适合重视长期保存、可迁移和本地控制的用户。",
            dayOffset = 40,
        ),
        demoItem(
            id = "tool-002-logseq",
            topicId = "topic-open-source-tools",
            type = ContentType.WEB_ARTICLE,
            title = "Logseq：大纲式笔记与日记流",
            summary = "以块和日记为核心，适合每日记录和任务整理。",
            tags = listOf("大纲", "日记", "开源"),
            sourceTitle = "Logseq 中文资料整理",
            sourceUrl = "https://logseq.com/",
            body = "Logseq 的核心是块引用和日记页面，适合把碎片想法按时间捕捉，再通过链接组织成主题。它的开源属性也适合强调可控性。",
            dayOffset = 41,
        ),
        demoItem(
            id = "tool-003-zotero",
            topicId = "topic-open-source-tools",
            type = ContentType.DOCUMENT,
            title = "Zotero：论文与网页资料管理",
            summary = "适合保存文献、网页快照和引用信息。",
            tags = listOf("文献管理", "引用", "PDF"),
            sourceTitle = "Zotero 中文使用资料整理",
            sourceUrl = "https://www.zotero.org/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "Zotero 可以管理论文、书籍和网页条目，并支持浏览器插件抓取元数据。对研究型资料库来说，它是结构化来源管理的重要工具。",
            dayOffset = 42,
        ),
        demoItem(
            id = "tool-004-omnivore",
            topicId = "topic-open-source-tools",
            type = ContentType.WEB_ARTICLE,
            title = "Omnivore：稍后读与高亮归档",
            summary = "把网页收藏、阅读、高亮和导出串起来。",
            tags = listOf("稍后读", "高亮", "归档"),
            sourceTitle = "Omnivore 中文资料整理",
            sourceUrl = "https://github.com/omnivore-app/omnivore",
            body = "稍后读工具的价值不只是保存链接，而是把阅读状态、高亮和标签保存下来。它适合演示从网页到资料库的收藏流程。",
            dayOffset = 43,
        ),
        demoItem(
            id = "tool-005-immich",
            topicId = "topic-open-source-tools",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "Immich：自托管照片备份",
            summary = "适合图像类资料管理示例，强调照片备份和本地控制。",
            tags = listOf("照片", "自托管", "备份"),
            sourceTitle = "Immich 开源项目资料整理",
            sourceUrl = "https://github.com/immich-app/immich",
            body = "Immich 是开源照片备份和管理工具，适合希望把个人图片资料放在自有服务器上的用户。演示卡片可以呈现图像资料不一定都有长文本。",
            dayOffset = 44,
        ),
        demoItem(
            id = "tool-006-local-first",
            topicId = "topic-open-source-tools",
            type = ContentType.WEB_ARTICLE,
            title = "Local-first 软件强调本地优先",
            summary = "本地优先不是拒绝云端，而是把数据主权和离线可用放在前面。",
            tags = listOf("Local-first", "离线", "数据主权"),
            sourceTitle = "Local-first 中文资料整理",
            sourceUrl = "https://www.inkandswitch.com/local-first/",
            body = "Local-first 软件强调数据先保存在用户设备上，再通过同步实现协作。它适合解释为什么资料应用要重视本地缓存、导出和可迁移格式。",
            dayOffset = 45,
        ),
        demoItem(
            id = "tool-007-affine",
            topicId = "topic-open-source-tools",
            type = ContentType.WEB_ARTICLE,
            title = "AFFiNE：文档、白板与知识库结合",
            summary = "开源生产力工具示例，适合对比 Notion 类产品。",
            tags = listOf("白板", "文档", "开源"),
            sourceTitle = "AFFiNE 中文资料整理",
            sourceUrl = "https://github.com/toeverything/AFFiNE",
            body = "AFFiNE 把文档编辑、白板和知识管理结合在一起，适合强调资料不仅是列表，还可以变成图形化组织和项目空间。",
            dayOffset = 46,
        ),
        demoItem(
            id = "tool-008-excalidraw",
            topicId = "topic-open-source-tools",
            type = ContentType.IMAGE_SCREENSHOT,
            title = "Excalidraw：手绘风图解工具",
            summary = "适合保存架构草图、流程图和灵感图。",
            tags = listOf("画图", "流程图", "草图"),
            sourceTitle = "Excalidraw 开源项目资料整理",
            sourceUrl = "https://github.com/excalidraw/excalidraw",
            body = "Excalidraw 适合快速画出架构图、产品流程和课堂笔记。资料应用可把这类图片作为图像条目保存，而不是强行要求所有资料都有正文。",
            dayOffset = 47,
        ),
        demoItem(
            id = "tool-009-pocketbase",
            topicId = "topic-open-source-tools",
            type = ContentType.WEB_ARTICLE,
            title = "PocketBase：轻量后端原型工具",
            summary = "单文件后端适合快速做账号、数据库和文件存储原型。",
            tags = listOf("后端", "原型", "数据库"),
            sourceTitle = "PocketBase 中文资料整理",
            sourceUrl = "https://pocketbase.io/",
            body = "PocketBase 提供轻量数据库、认证、文件存储和管理后台。对演示应用来说，它适合解释为什么原型阶段可以先用轻量后端验证流程。",
            dayOffset = 48,
        ),
        demoItem(
            id = "tool-010-open-webui",
            topicId = "topic-open-source-tools",
            type = ContentType.WEB_ARTICLE,
            title = "Open WebUI：本地模型聊天界面",
            summary = "适合展示本地模型、私有化部署和模型管理的工具链。",
            tags = listOf("本地模型", "LLM", "界面"),
            sourceTitle = "Open WebUI 开源项目资料整理",
            sourceUrl = "https://github.com/open-webui/open-webui",
            body = "Open WebUI 常用于连接本地模型服务，提供类似聊天产品的交互界面。它适合演示本地 AI 工具如何降低模型使用门槛。",
            dayOffset = 49,
        ),
        demoItem(
            id = "km-001-para",
            topicId = "topic-knowledge-workflows",
            type = ContentType.WEB_ARTICLE,
            title = "PARA：按项目、领域、资源、归档组织资料",
            summary = "PARA 适合把资料从收藏夹转成可行动的结构。",
            tags = listOf("PARA", "分类", "归档"),
            sourceTitle = "PARA 方法中文资料整理",
            sourceUrl = "https://fortelabs.com/blog/para/",
            body = "PARA 把信息分成项目、领域、资源和归档。它的重点不是建立完美分类，而是让资料能服务当前行动，同时让过期内容进入归档。",
            dayOffset = 50,
        ),
        demoItem(
            id = "km-002-progressive-summarization",
            topicId = "topic-knowledge-workflows",
            type = ContentType.DOCUMENT,
            title = "渐进式摘要：先保存，再逐层提炼",
            summary = "从原文、高亮、摘要到行动项，逐步降低阅读负担。",
            tags = listOf("摘要", "高亮", "复用"),
            sourceTitle = "渐进式摘要中文资料整理",
            sourceUrl = "https://fortelabs.com/blog/progressive-summarization/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "渐进式摘要鼓励先捕捉原始材料，再在多次回看中提炼重点。它适合解释为什么资料库需要保留来源、摘要和标签，而不是只存一个标题。",
            dayOffset = 51,
        ),
        demoItem(
            id = "km-003-zettelkasten",
            topicId = "topic-knowledge-workflows",
            type = ContentType.WEB_ARTICLE,
            title = "卡片盒笔记强调原子化和连接",
            summary = "每张卡片表达一个观点，并通过链接形成知识网络。",
            tags = listOf("卡片盒", "原子笔记", "链接"),
            sourceTitle = "卡片盒笔记中文资料整理",
            sourceUrl = "https://zettelkasten.de/",
            body = "卡片盒笔记不是把文章剪成碎片，而是把理解后的观点写成独立卡片，再通过链接建立长期可扩展的思考网络。",
            dayOffset = 52,
        ),
        demoItem(
            id = "km-004-inbox-zero",
            topicId = "topic-knowledge-workflows",
            type = ContentType.DOCUMENT,
            title = "资料收件箱需要定期清空",
            summary = "收藏只是第一步，后续要判断、归类、删除或转行动。",
            tags = listOf("收件箱", "清理", "工作流"),
            sourceTitle = "知识管理收件箱中文资料整理",
            sourceUrl = "https://sspai.com/",
            documentFormat = DocumentFormat.TXT,
            body = "资料应用最容易变成新的垃圾箱。更好的工作流是把新内容先进入收件箱，然后定期处理：有用的归类，无用的删除，需要行动的转成任务。",
            dayOffset = 53,
        ),
        demoItem(
            id = "km-005-source-trace",
            topicId = "topic-knowledge-workflows",
            type = ContentType.WEB_ARTICLE,
            title = "可追溯来源比漂亮摘要更重要",
            summary = "资料卡必须保留来源链接、时间和上下文，方便复核。",
            tags = listOf("来源", "复核", "可信度"),
            sourceTitle = "信息可信度与引用管理资料整理",
            sourceUrl = "https://zh.wikipedia.org/wiki/引用",
            body = "摘要可以帮助快速浏览，但不能替代来源。尤其是 AI 生成摘要时，必须保留链接、采集时间和原始片段，方便用户回到原文复查。",
            dayOffset = 54,
        ),
        demoItem(
            id = "km-006-tag-taxonomy",
            topicId = "topic-knowledge-workflows",
            type = ContentType.WEB_ARTICLE,
            title = "标签体系不宜过细",
            summary = "标签用于检索和筛选，过多会让用户无法维护。",
            tags = listOf("标签", "筛选", "分类"),
            sourceTitle = "标签系统设计中文资料整理",
            sourceUrl = "https://www.uisdc.com/",
            body = "标签应该服务筛选，而不是制造管理负担。一个资料卡有两三个稳定标签通常足够，过细的标签会导致重复、同义词和长期维护问题。",
            dayOffset = 55,
        ),
        demoItem(
            id = "km-007-reading-queue",
            topicId = "topic-knowledge-workflows",
            type = ContentType.WEB_ARTICLE,
            title = "阅读队列要区分待读、精读和归档",
            summary = "不同阅读状态需要不同展示，而不是都混在收藏夹里。",
            tags = listOf("阅读队列", "状态", "待读"),
            sourceTitle = "稍后读工作流中文资料整理",
            sourceUrl = "https://sspai.com/",
            body = "不是所有收藏都值得精读。资料系统可以把内容分成待读、已读、精读、归档和删除，让用户知道每条资料处于什么状态。",
            dayOffset = 56,
        ),
        demoItem(
            id = "km-008-ai-summary",
            topicId = "topic-knowledge-workflows",
            type = ContentType.DOCUMENT,
            title = "AI 摘要适合做初筛，不适合替代判断",
            summary = "AI 可以快速提炼主题，但需要保留人工复核入口。",
            tags = listOf("AI 摘要", "初筛", "人工复核"),
            sourceTitle = "AI 知识管理中文资料整理",
            sourceUrl = "https://www.infoq.cn/",
            documentFormat = DocumentFormat.MARKDOWN,
            body = "AI 摘要能帮用户快速判断一篇资料是否值得看，但它也可能遗漏细节或误解语气。更稳妥的设计是把 AI 摘要当作初筛层，并保留原文入口。",
            dayOffset = 57,
        ),
        demoItem(
            id = "km-009-review-cadence",
            topicId = "topic-knowledge-workflows",
            type = ContentType.WEB_ARTICLE,
            title = "定期回顾让资料重新变成资产",
            summary = "资料库需要周回顾或月回顾，把沉淀内容重新连接到项目。",
            tags = listOf("回顾", "复盘", "资产"),
            sourceTitle = "个人知识管理回顾方法资料整理",
            sourceUrl = "https://sspai.com/",
            body = "资料如果从不回看，就只是静态仓库。定期回顾可以把旧资料重新关联到当前问题，形成选题、决策和创作素材。",
            dayOffset = 58,
        ),
        demoItem(
            id = "km-010-export",
            topicId = "topic-knowledge-workflows",
            type = ContentType.DOCUMENT,
            title = "长期资料库必须考虑导出和迁移",
            summary = "开放格式比封闭数据库更适合长期保存。",
            tags = listOf("导出", "迁移", "开放格式"),
            sourceTitle = "开放格式与知识库迁移资料整理",
            sourceUrl = "https://commonmark.org/",
            documentFormat = DocumentFormat.TXT,
            body = "长期知识库不能完全依赖单一应用。Markdown、图片文件、来源链接和结构化元数据更容易迁移，也更适合未来接入新的 AI 工具。",
            dayOffset = 59,
        ),
    )

    val defaultAiEngineSettings = AiEngineSettings(localModelId = GEMMA_4_E4B_IT.id)

    private fun demoTopic(id: String, title: String, color: String, index: Int): Topic = Topic(
        id = id,
        title = title,
        iconName = if (index % 2 == 0) "folder-spark" else "folder-bookmark",
        iconColor = color,
        updatedAtEpochMillis = BASE_TIME - index * DAY_MILLIS,
    )

    private fun demoItem(
        id: String,
        topicId: String,
        type: ContentType,
        title: String,
        summary: String,
        tags: List<String>,
        sourceTitle: String,
        sourceUrl: String?,
        body: String,
        dayOffset: Int,
        documentFormat: DocumentFormat? = null,
    ): KnowledgeItem = KnowledgeItem(
        id = "demo-$id",
        topicId = topicId,
        contentType = type,
        title = title,
        summary = summary,
        fullText = buildString {
            appendLine("标签：${tags.joinToString(" · ")}")
            appendLine("来源：$sourceTitle")
            appendLine("采集时间：2026-06-${(28 - dayOffset % 20).toString().padStart(2, '0')}")
            appendLine()
            appendLine(body)
        },
        sourceUrl = sourceUrl,
        documentFormat = documentFormat,
        createdAtEpochMillis = BASE_TIME - dayOffset * DAY_MILLIS,
    )

    private const val BASE_TIME = 1_719_532_800_000L
    private const val DAY_MILLIS = 86_400_000L
}
